name = "nav-website"
main = "worker.js"  # 入口文件路径
compatibility_date = "2025-07-17"

[build]
command = "npm run build"
upload_dir = "public"

[[kv_namespaces]]
binding = "NAV_DB"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_ID"

[pages]
bucket = "public"